#!/bin/sh

set -e

#DEBHELPER#

is_chroot() {
    if command -v ischroot >/dev/null 2>&1; then
        ischroot && return 0 || return 1
    else
        # fallback到其他方法
        [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]
    fi
}

case "$1" in
  configure)
    if is_chroot; then
        echo "Skipping GRUB update in chroot environment"
    else
        if [ ! -f "/etc/default/grub.d/spdk.cfg" ]; then
            arch=$(uname -m)
            if [ "$arch" = "x86_64" ];then
                iommu="intel_iommu=on iommu=pt amd_iommu=on"
            fi
            echo "GRUB_CMDLINE_LINUX=\"hugepagesz=2M hugepages=2048 $iommu\"" >/etc/default/grub.d/spdk.cfg
            update-grub
        fi
        systemctl enable pxvirt-spdk.service pxvirt-spdk-tgt.service
    fi
    ;;

esac

exit 0